src/Entity/life/ProfilSinusGorge.php
<?php

namespace App\Entity\life;

use App\Entity\FicheClient;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProfilSinusGorgeRepository;

/**
 * @ORM\Entity(repositoryClass=ProfilSinusGorgeRepository::class)
 */
class ProfilSinusGorge
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $transfert;

    /**
     * @ORM\Column(type="text")
     */
    private $choix_bio_specifique;

    /**
     * @ORM\Column(type="text")
     */
    private $choix_items;

    /**
     * @ORM\ManyToOne(targetEntity=FicheClient::class, inversedBy="sinus_gorge")
     */
    private $ficheClient;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTransfert(): ?string
    {
        return $this->transfert;
    }

    public function setTransfert(string $transfert): self
    {
        $this->transfert = $transfert;

        return $this;
    }

    public function getChoixBioSpecifique(): ?string
    {
        return $this->choix_bio_specifique;
    }

    public function setChoixBioSpecifique(string $choix_bio_specifique): self
    {
        $this->choix_bio_specifique = $choix_bio_specifique;

        return $this;
    }

    public function getChoixItems(): ?string
    {
        return $this->choix_items;
    }

    public function setChoixItems(string $choix_items): self
    {
        $this->choix_items = $choix_items;

        return $this;
    }

    public function getFicheClient(): ?FicheClient
    {
        return $this->ficheClient;
    }

    public function setFicheClient(?FicheClient $ficheClient): self
    {
        $this->ficheClient = $ficheClient;

        return $this;
    }
}

src/Form/ProfilSinusGorgeType.php
<?php

namespace App\Form;

use App\Entity\ProfilSinusGorge;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProfilSinusGorgeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('transfert')
            ->add('choix_bio_specifique')
            ->add('choix_items')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ProfilSinusGorge::class,
        ]);
    }
}

src/Controller/ProfilSinusGorgeController.php
<?php

namespace App\Controller;

use App\Entity\life\ProfilSinusGorge;
use App\Form\ProfilSinusGorgeType;
use App\Repository\ProfilSinusGorgeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/profil/sinus/gorge")
 */
class ProfilSinusGorgeController extends AbstractController
{
    /**
     * @Route("/", name="app_profil_sinus_gorge_index", methods={"GET"})
     */
    public function index(ProfilSinusGorgeRepository $profilSinusGorgeRepository): Response
    {
        return $this->render('profil_sinus_gorge/index.html.twig', [
            'profil_sinus_gorges' => $profilSinusGorgeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_profil_sinus_gorge_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ProfilSinusGorgeRepository $profilSinusGorgeRepository): Response
    {
        $profilSinusGorge = new ProfilSinusGorge();
        $form = $this->createForm(ProfilSinusGorgeType::class, $profilSinusGorge);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $profilSinusGorgeRepository->add($profilSinusGorge);
            return $this->redirectToRoute('app_profil_sinus_gorge_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('profil_sinus_gorge/new.html.twig', [
            'profil_sinus_gorge' => $profilSinusGorge,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_profil_sinus_gorge_show", methods={"GET"})
     */
    public function show(ProfilSinusGorge $profilSinusGorge): Response
    {
        return $this->render('profil_sinus_gorge/show.html.twig', [
            'profil_sinus_gorge' => $profilSinusGorge,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_profil_sinus_gorge_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, ProfilSinusGorge $profilSinusGorge, ProfilSinusGorgeRepository $profilSinusGorgeRepository): Response
    {
        $form = $this->createForm(ProfilSinusGorgeType::class, $profilSinusGorge);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $profilSinusGorgeRepository->add($profilSinusGorge);
            return $this->redirectToRoute('app_profil_sinus_gorge_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('profil_sinus_gorge/edit.html.twig', [
            'profil_sinus_gorge' => $profilSinusGorge,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_profil_sinus_gorge_delete", methods={"POST"})
     */
    public function delete(Request $request, ProfilSinusGorge $profilSinusGorge, ProfilSinusGorgeRepository $profilSinusGorgeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$profilSinusGorge->getId(), $request->request->get('_token'))) {
            $profilSinusGorgeRepository->remove($profilSinusGorge);
        }

        return $this->redirectToRoute('app_profil_sinus_gorge_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/profil_sinus_gorge/_delete_form.html.twig
<form method="post" action="{{ path('app_profil_sinus_gorge_delete', {'id': profil_sinus_gorge.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ profil_sinus_gorge.id) }}">
    <button class="btn">Delete</button>
</form>

templates/profil_sinus_gorge/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ProfilSinusGorge{% endblock %}

{% block body %}
    <h1>Edit ProfilSinusGorge</h1>

    {{ include('profil_sinus_gorge/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_profil_sinus_gorge_index') }}">back to list</a>

    {{ include('profil_sinus_gorge/_delete_form.html.twig') }}
{% endblock %}

templates/profil_sinus_gorge/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ProfilSinusGorge index{% endblock %}

{% block body %}
    <h1>ProfilSinusGorge index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Transfert</th>
                <th>Choix_bio_specifique</th>
                <th>Choix_items</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for profil_sinus_gorge in profil_sinus_gorges %}
            <tr>
                <td>{{ profil_sinus_gorge.id }}</td>
                <td>{{ profil_sinus_gorge.transfert }}</td>
                <td>{{ profil_sinus_gorge.choixBioSpecifique }}</td>
                <td>{{ profil_sinus_gorge.choixItems }}</td>
                <td>
                    <a href="{{ path('app_profil_sinus_gorge_show', {'id': profil_sinus_gorge.id}) }}">show</a>
                    <a href="{{ path('app_profil_sinus_gorge_edit', {'id': profil_sinus_gorge.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_profil_sinus_gorge_new') }}">Create new</a>
{% endblock %}

templates/profil_sinus_gorge/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ProfilSinusGorge{% endblock %}

{% block body %}
    <h1>Create new ProfilSinusGorge</h1>

    {{ include('profil_sinus_gorge/_form.html.twig') }}

    <a href="{{ path('app_profil_sinus_gorge_index') }}">back to list</a>
{% endblock %}

templates/profil_sinus_gorge/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ProfilSinusGorge{% endblock %}

{% block body %}
    <h1>ProfilSinusGorge</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ profil_sinus_gorge.id }}</td>
            </tr>
            <tr>
                <th>Transfert</th>
                <td>{{ profil_sinus_gorge.transfert }}</td>
            </tr>
            <tr>
                <th>Choix_bio_specifique</th>
                <td>{{ profil_sinus_gorge.choixBioSpecifique }}</td>
            </tr>
            <tr>
                <th>Choix_items</th>
                <td>{{ profil_sinus_gorge.choixItems }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_profil_sinus_gorge_index') }}">back to list</a>

    <a href="{{ path('app_profil_sinus_gorge_edit', {'id': profil_sinus_gorge.id}) }}">edit</a>

    {{ include('profil_sinus_gorge/_delete_form.html.twig') }}
{% endblock %}