src/Entity/life/ProfilNutrition.php
<?php

namespace App\Entity\life;

use App\Entity\FicheClient;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProfilNutritionRepository;

/**
 * @ORM\Entity(repositoryClass=ProfilNutritionRepository::class)
 */
class ProfilNutrition
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mineraux;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $acides_amines;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $vitamines;

    /**
     * @ORM\ManyToOne(targetEntity=FicheClient::class, inversedBy="nutrition")
     */
    private $ficheClient;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMineraux(): ?string
    {
        return $this->mineraux;
    }

    public function setMineraux(string $mineraux): self
    {
        $this->mineraux = $mineraux;

        return $this;
    }

    public function getAcidesAmines(): ?string
    {
        return $this->acides_amines;
    }

    public function setAcidesAmines(string $acides_amines): self
    {
        $this->acides_amines = $acides_amines;

        return $this;
    }

    public function getVitamines(): ?string
    {
        return $this->vitamines;
    }

    public function setVitamines(string $vitamines): self
    {
        $this->vitamines = $vitamines;

        return $this;
    }

    public function getFicheClient(): ?FicheClient
    {
        return $this->ficheClient;
    }

    public function setFicheClient(?FicheClient $ficheClient): self
    {
        $this->ficheClient = $ficheClient;

        return $this;
    }
}

src/Form/ProfilNutritionType.php
<?php

namespace App\Form;

use App\Entity\AcidesAmines;
use App\Entity\Meridien;
use App\Entity\Mineraux;
use App\Entity\ProfilNutrition;
use App\Entity\Vitamines;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProfilNutritionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('mineraux',EntityType::class,[
                "class" => Mineraux::class,
                "label" => "Les minéraux"
            ])
            ->add('acides_amines',EntityType::class,[
        "class" => AcidesAmines::class,
        "label" => "Les acides aminés"
    ])
            ->add('vitamines',EntityType::class,[
                "class" => Vitamines::class,
                "label" => "Les vitamines"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ProfilNutrition::class,
        ]);
    }
}

src/Controller/ProfilNutritionController.php
<?php

namespace App\Controller;

use App\Entity\life\ProfilNutrition;
use App\Form\ProfilNutritionType;
use App\Repository\ProfilNutritionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/profil/nutrition")
 */
class ProfilNutritionController extends AbstractController
{
    /**
     * @Route("/", name="app_profil_nutrition_index", methods={"GET"})
     */
    public function index(ProfilNutritionRepository $profilNutritionRepository): Response
    {
        return $this->render('profil_nutrition/index.html.twig', [
            'profil_nutritions' => $profilNutritionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_profil_nutrition_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ProfilNutritionRepository $profilNutritionRepository): Response
    {
        $profilNutrition = new ProfilNutrition();
        $form = $this->createForm(ProfilNutritionType::class, $profilNutrition);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $profilNutritionRepository->add($profilNutrition);
            return $this->redirectToRoute('app_profil_nutrition_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('profil_nutrition/new.html.twig', [
            'profil_nutrition' => $profilNutrition,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_profil_nutrition_show", methods={"GET"})
     */
    public function show(ProfilNutrition $profilNutrition): Response
    {
        return $this->render('profil_nutrition/show.html.twig', [
            'profil_nutrition' => $profilNutrition,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_profil_nutrition_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, ProfilNutrition $profilNutrition, ProfilNutritionRepository $profilNutritionRepository): Response
    {
        $form = $this->createForm(ProfilNutritionType::class, $profilNutrition);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $profilNutritionRepository->add($profilNutrition);
            return $this->redirectToRoute('app_profil_nutrition_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('profil_nutrition/edit.html.twig', [
            'profil_nutrition' => $profilNutrition,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_profil_nutrition_delete", methods={"POST"})
     */
    public function delete(Request $request, ProfilNutrition $profilNutrition, ProfilNutritionRepository $profilNutritionRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$profilNutrition->getId(), $request->request->get('_token'))) {
            $profilNutritionRepository->remove($profilNutrition);
        }

        return $this->redirectToRoute('app_profil_nutrition_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/profil_nutrition/_delete_form.html.twig
<form method="post" action="{{ path('app_profil_nutrition_delete', {'id': profil_nutrition.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ profil_nutrition.id) }}">
    <button class="btn">Delete</button>
</form>

templates/profil_nutrition/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ProfilNutrition{% endblock %}

{% block body %}
    <h1>Edit ProfilNutrition</h1>

    {{ include('profil_nutrition/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_profil_nutrition_index') }}">back to list</a>

    {{ include('profil_nutrition/_delete_form.html.twig') }}
{% endblock %}

templates/profil_nutrition/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ProfilNutrition index{% endblock %}

{% block body %}
    <h1>ProfilNutrition index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Mineraux</th>
                <th>Acides_amines</th>
                <th>Vitamines</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for profil_nutrition in profil_nutritions %}
            <tr>
                <td>{{ profil_nutrition.id }}</td>
                <td>{{ profil_nutrition.mineraux }}</td>
                <td>{{ profil_nutrition.acidesAmines }}</td>
                <td>{{ profil_nutrition.vitamines }}</td>
                <td>
                    <a href="{{ path('app_profil_nutrition_show', {'id': profil_nutrition.id}) }}">show</a>
                    <a href="{{ path('app_profil_nutrition_edit', {'id': profil_nutrition.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_profil_nutrition_new') }}">Create new</a>
{% endblock %}

templates/profil_nutrition/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ProfilNutrition{% endblock %}

{% block body %}
    <h1>Create new ProfilNutrition</h1>

    {{ include('profil_nutrition/_form.html.twig') }}

    <a href="{{ path('app_profil_nutrition_index') }}">back to list</a>
{% endblock %}

templates/profil_nutrition/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ProfilNutrition{% endblock %}

{% block body %}
    <h1>ProfilNutrition</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ profil_nutrition.id }}</td>
            </tr>
            <tr>
                <th>Mineraux</th>
                <td>{{ profil_nutrition.mineraux }}</td>
            </tr>
            <tr>
                <th>Acides_amines</th>
                <td>{{ profil_nutrition.acidesAmines }}</td>
            </tr>
            <tr>
                <th>Vitamines</th>
                <td>{{ profil_nutrition.vitamines }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_profil_nutrition_index') }}">back to list</a>

    <a href="{{ path('app_profil_nutrition_edit', {'id': profil_nutrition.id}) }}">edit</a>

    {{ include('profil_nutrition/_delete_form.html.twig') }}
{% endblock %}